package com.liuxinyang.ai_scheduleassistant.ui.theme

import androidx.compose.ui.graphics.Color

// AUTO-GENERATED by theme/gen_theme.py from theme/tokens.json — DO NOT EDIT.

/** 一套完整配色。modules 的下标顺序 == Modules.colorIndex(), 由生成器保证。 */
data class ThemePalette(
    val key: String,
    val label: String,
    val isDark: Boolean,
    val bg: Color,
    val card: Color,
    val card2: Color,
    val line: Color,
    val fg: Color,
    val muted: Color,
    val accent: Color,
    val onAccent: Color,
    val chipBg: Color,
    val ok: Color,
    val warn: Color,
    val danger: Color,
    val modules: List<Color>,
    val cardRadius: Int,
    val buttonRadius: Int,
    val cellRadius: Int,
    val markerBar: Boolean,
    val markerSize: Int,
) {
    /** 与 Palette.of() 语义一致, 但走当前主题。 */
    fun moduleOf(module: String): Color =
        modules[com.liuxinyang.ai_scheduleassistant.data.Modules.colorIndex(module)]
}

object Tokens {
    /** 纸感 — 暖米白 + 衬线标题，像一本高质量手账。适合长时间看课表。 */
    val PAPER = ThemePalette(
        key = "paper",
        label = "纸感",
        isDark = false,
        bg = Color(0xFFFAF8F5),
        card = Color(0xFFFFFFFF),
        card2 = Color(0xFFF5F2EC),
        line = Color(0xFFE9E4DC),
        fg = Color(0xFF1C1B19),
        muted = Color(0xFF8A8580),
        accent = Color(0xFF3D5AFE),
        onAccent = Color(0xFFFFFFFF),
        chipBg = Color(0xFFF0ECE5),
        ok = Color(0xFF2E7D32),
        warn = Color(0xFFA66A00),
        danger = Color(0xFFC62828),
        // 顺序: class, exam, meeting, assignment, alarm, reminder, memo
        modules = listOf(
            Color(0xFF2B5FD9),
            Color(0xFFC62828),
            Color(0xFF7C4DFF),
            Color(0xFF8A7A00),
            Color(0xFFB26A00),
            Color(0xFF1E8E3E),
            Color(0xFF6B7A8F),
        ),
        cardRadius = 16,
        buttonRadius = 12,
        cellRadius = 10,
        markerBar = false,
        markerSize = 5,
    )

    /** 夜航 — 近黑底 + 高对比，类似 Linear/Vercel 的暗色后台。适合夜间与开发者审美。 */
    val NIGHT = ThemePalette(
        key = "night",
        label = "夜航",
        isDark = true,
        bg = Color(0xFF0E1116),
        card = Color(0xFF161B22),
        card2 = Color(0xFF1B2129),
        line = Color(0xFF252C37),
        fg = Color(0xFFE6E8EB),
        muted = Color(0xFF7D8B9A),
        accent = Color(0xFF3D7EFF),
        onAccent = Color(0xFFFFFFFF),
        chipBg = Color(0xFF1C2430),
        ok = Color(0xFF3FB950),
        warn = Color(0xFFD29922),
        danger = Color(0xFFF85149),
        // 顺序: class, exam, meeting, assignment, alarm, reminder, memo
        modules = listOf(
            Color(0xFF3D7EFF),
            Color(0xFFF85149),
            Color(0xFFC9A6FF),
            Color(0xFFD3D95F),
            Color(0xFFF0B357),
            Color(0xFF3FB950),
            Color(0xFF8FA3B8),
        ),
        cardRadius = 12,
        buttonRadius = 9,
        cellRadius = 8,
        markerBar = true,
        markerSize = 3,
    )

    val DEFAULT_KEY = "night"
    val all: List<ThemePalette> = listOf(PAPER, NIGHT)
    val default: ThemePalette = NIGHT

    fun byKey(key: String): ThemePalette =
        all.firstOrNull { it.key == key } ?: default
}
